name: shdownloader
version: 1.0.0-SNAPSHOT
main: me.vanes430.shdownloader.spigot.ShDownloaderSpigot
api-version: 1.20
folia-supported: true
commands:
  shdown:
    description: Download a file from a link
    permission: shdownloader.use
